/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.openmarket.presentation;

import co.edu.unicauca.openmarket.domain.Category;
import co.edu.unicauca.openmarket.domain.Product;
import co.edu.unicauca.openmarket.domain.service.CategoryService;
import co.edu.unicauca.openmarket.domain.service.ProductService;
import co.edu.unicauca.openmarket.infra.Messages;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dafer
 */
public class GUIProductsCategory extends javax.swing.JFrame {
    
    private CategoryService categoryService;
    private int addOption;
    /**
     * Creates new form GUIProductsCategory
     */
    public GUIProductsCategory(java.awt.Frame parent, boolean modal, CategoryService categoryService) {
        initComponents();
        this.categoryService = categoryService;
        stateInitial();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSouth = new javax.swing.JPanel();
        btnNuevaCategoria = new javax.swing.JButton();
        btnSaveCategory = new javax.swing.JButton();
        btnEditarCategoria = new javax.swing.JButton();
        btnEliminarCategoria = new javax.swing.JButton();
        btnListarCategoria = new javax.swing.JButton();
        btnCancelarCategoria = new javax.swing.JButton();
        btnCerrarCategoria = new javax.swing.JButton();
        pnlListarCategoria = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        pnlIngresarCategoria = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCategoriaId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        pnlSouth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNuevaCategoria.setText("Nuevo");
        btnNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCategoriaActionPerformed(evt);
            }
        });
        pnlSouth.add(btnNuevaCategoria);

        btnSaveCategory.setText("Grabar");
        btnSaveCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCategoryActionPerformed(evt);
            }
        });
        pnlSouth.add(btnSaveCategory);

        btnEditarCategoria.setText("Editar");
        btnEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCategoriaActionPerformed(evt);
            }
        });
        pnlSouth.add(btnEditarCategoria);

        btnEliminarCategoria.setText("Eliminar");
        btnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCategoriaActionPerformed(evt);
            }
        });
        pnlSouth.add(btnEliminarCategoria);

        btnListarCategoria.setText("Listar");
        btnListarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCategoriaActionPerformed(evt);
            }
        });
        pnlSouth.add(btnListarCategoria);

        btnCancelarCategoria.setText("Cancelar");
        btnCancelarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCategoriaActionPerformed(evt);
            }
        });
        pnlSouth.add(btnCancelarCategoria);

        btnCerrarCategoria.setText("Cerrar");
        btnCerrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCategoriaActionPerformed(evt);
            }
        });
        pnlSouth.add(btnCerrarCategoria);

        getContentPane().add(pnlSouth, java.awt.BorderLayout.PAGE_END);

        pnlListarCategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lista de Categorias");

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCategorias);

        javax.swing.GroupLayout pnlListarCategoriaLayout = new javax.swing.GroupLayout(pnlListarCategoria);
        pnlListarCategoria.setLayout(pnlListarCategoriaLayout);
        pnlListarCategoriaLayout.setHorizontalGroup(
            pnlListarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlListarCategoriaLayout.setVerticalGroup(
            pnlListarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarCategoriaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlListarCategoria, java.awt.BorderLayout.CENTER);

        pnlIngresarCategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categoria");

        jLabel2.setText("Nombre:");

        jLabel7.setText("Id:");

        txtCategoriaId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCategoriaIdFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlIngresarCategoriaLayout = new javax.swing.GroupLayout(pnlIngresarCategoria);
        pnlIngresarCategoria.setLayout(pnlIngresarCategoriaLayout);
        pnlIngresarCategoriaLayout.setHorizontalGroup(
            pnlIngresarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngresarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngresarCategoriaLayout.createSequentialGroup()
                        .addGroup(pnlIngresarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlIngresarCategoriaLayout.createSequentialGroup()
                                .addGap(0, 13, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngresarCategoriaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(pnlIngresarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCategoriaId, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        pnlIngresarCategoriaLayout.setVerticalGroup(
            pnlIngresarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarCategoriaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnlIngresarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoriaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIngresarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        getContentPane().add(pnlIngresarCategoria, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initializeTable() {
        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Name"
                }
        ));
    }
    private void fillTable(List<Category> categorias) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblCategorias.getModel();

        Object rowData[] = new Object[3];//No columnas
        for (int i = 0; i < categorias.size(); i++) {
            rowData[0] = categorias.get(i).getCategoryId();
            rowData[1] = categorias.get(i).getName();
            
            model.addRow(rowData);
        }
    }
   
    private void btnSaveCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCategoryActionPerformed
        if(addOption == 1){
            if (txtNombreCategoria.getText().trim().equals("")) {
                Messages.showMessageDialog("Debe ingresar el nombre de la categoria", "Atención");
                txtNombreCategoria.requestFocus();
                return;
            }else{
                //Agregar
                addCategory();
            }
        }else if(addOption == 2){
            if (txtNombreCategoria.getText().trim().equals("")) {
                Messages.showMessageDialog("Debe ingresar un nuevo nombre de la categoria", "Atención");
                txtNombreCategoria.requestFocus();
                return;
            }else if(txtCategoriaId.getText().trim().equals("")){
                Messages.showMessageDialog("Debe ingresar el id de la categoria", "Atención");
                txtCategoriaId.requestFocus();
                return;
            }else{
                //Editar
                editCategory();
            }
        }else if(addOption == 3){
            if(txtCategoriaId.getText().trim().equals("")){
                Messages.showMessageDialog("Debe ingresar el id de la categoria", "Atención");
                txtCategoriaId.requestFocus();
                return;
            }else{
                //Eliminar
                deleteCategory();
            }
        }
        stateInitial(); 
    }//GEN-LAST:event_btnSaveCategoryActionPerformed

    private void btnListarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCategoriaActionPerformed
        fillTable(categoryService.findAllCategorys());
    }//GEN-LAST:event_btnListarCategoriaActionPerformed

    private void btnCerrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCategoriaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarCategoriaActionPerformed

    private void btnNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCategoriaActionPerformed
        stateNew();
        txtNombreCategoria.requestFocus();
        addOption=1;
    }//GEN-LAST:event_btnNuevaCategoriaActionPerformed

    private void btnEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCategoriaActionPerformed
        stateEdit();
        txtCategoriaId.requestFocus();
        addOption=2;
    }//GEN-LAST:event_btnEditarCategoriaActionPerformed

    private void btnCancelarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCategoriaActionPerformed
        stateInitial();
        cleanControls();
    }//GEN-LAST:event_btnCancelarCategoriaActionPerformed

    private void btnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCategoriaActionPerformed
        stateDelete();
        txtCategoriaId.requestFocus();
        addOption=3;
    }//GEN-LAST:event_btnEliminarCategoriaActionPerformed

    private void txtCategoriaIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCategoriaIdFocusLost
        if (txtCategoriaId.getText().trim().equals("")) {
            return;
        }
        try{
            Long categoriaId = Long.parseLong(txtCategoriaId.getText());
            Category cat = categoryService.findCategory(categoriaId);
            if (cat == null) {
                txtCategoriaId.setText("");
                Messages.showMessageDialog("El identificador de la categoria no existe", "Error");
                txtCategoriaId.requestFocus();
            } else {
                txtNombreCategoria.setText(cat.getName());
            }
        }catch(NumberFormatException ex){
            txtCategoriaId.setText("");
            Messages.showMessageDialog("Ingrese un numero", "Error");
            return;
        }
    }//GEN-LAST:event_txtCategoriaIdFocusLost

    private void addCategory() {
        String name = txtNombreCategoria.getText().trim();

        if (categoryService.saveCategory(name)) {
            Messages.showMessageDialog("Se grabó con éxito", "Atención");
            cleanControls();
            
        } else {
            Messages.showMessageDialog("Error al grabar, lo siento mucho", "Atención");
        }
    }
    
    private void editCategory(){
        Long id = Long.parseLong(txtCategoriaId.getText());
        
        Category categoria = new Category();
        categoria.setName(txtNombreCategoria.getText());
        
        if(categoryService.editCategory(id, categoria)){
            Messages.showMessageDialog("Se editó con éxito", "Atención");
            cleanControls();
            stateInitial();
        } else {
            Messages.showMessageDialog("Error al editar, lo siento mucho", "Atención");
        }
    }
    
    private void deleteCategory(){
        String id = txtCategoriaId.getText().trim();
        if (id.equals("")) {
            Messages.showMessageDialog("Debe buscar la categoria a eliminar", "Atención");
            txtCategoriaId.requestFocus();
            return;
        }
        Long categoryId = Long.parseLong(id);
        if (Messages.showConfirmDialog("Está seguro que desea eliminar esta categoria?", "Confirmación") == JOptionPane.YES_NO_OPTION) {
            if (categoryService.deleteCategory(categoryId)) {
                Messages.showMessageDialog("Categoria eliminada con éxito", "Atención");
                stateInitial();
            }
        }
        cleanControls();
    }
    
    private void cleanControls() {
        txtCategoriaId.setText("");
        txtNombreCategoria.setText("");
    }
    
    private void stateInitial() {
        //Botones de la barra de abajo en orden de izquierda a derecha
        btnNuevaCategoria.setVisible(true);
        btnSaveCategory.setVisible(false);
        btnEditarCategoria.setVisible(true);
        btnEliminarCategoria.setVisible(true);
        btnListarCategoria.setVisible(true);
        btnCancelarCategoria.setVisible(false);
        btnCerrarCategoria.setVisible(true);
        //Los campos de categoria
        txtCategoriaId.setEnabled(false);
        txtNombreCategoria.setEnabled(false);
    }
    
    private void stateNew(){
        //Botones de la barra de abajo en orden de izquierda a derecha
        btnNuevaCategoria.setVisible(false);
        btnSaveCategory.setVisible(true);
        btnEditarCategoria.setVisible(false);
        btnEliminarCategoria.setVisible(false);
        btnListarCategoria.setVisible(false);
        btnCancelarCategoria.setVisible(true);
        btnCerrarCategoria.setVisible(false);
        //Los campos de categoria
        txtCategoriaId.setEnabled(false);
        txtNombreCategoria.setEnabled(true);
    }
    
    private void stateEdit(){
        //Botones de la barra de abajo en orden de izquierda a derecha
        btnNuevaCategoria.setVisible(false);
        btnSaveCategory.setVisible(true);
        btnEditarCategoria.setVisible(false);
        btnEliminarCategoria.setVisible(false);
        btnListarCategoria.setVisible(false);
        btnCancelarCategoria.setVisible(true);
        btnCerrarCategoria.setVisible(false);
        //Los campos de categoria
        txtCategoriaId.setEnabled(true);
        txtNombreCategoria.setEnabled(true);
    }
    
    private void stateDelete(){
        //Botones de la barra de abajo en orden de izquierda a derecha
        btnNuevaCategoria.setVisible(false);
        btnSaveCategory.setVisible(true);
        btnEditarCategoria.setVisible(false);
        btnEliminarCategoria.setVisible(false);
        btnListarCategoria.setVisible(false);
        btnCancelarCategoria.setVisible(true);
        btnCerrarCategoria.setVisible(false);
        //Los campos de categoria
        txtCategoriaId.setEnabled(true);
        txtNombreCategoria.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCategoria;
    private javax.swing.JButton btnCerrarCategoria;
    private javax.swing.JButton btnEditarCategoria;
    private javax.swing.JButton btnEliminarCategoria;
    private javax.swing.JButton btnListarCategoria;
    private javax.swing.JButton btnNuevaCategoria;
    private javax.swing.JButton btnSaveCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlIngresarCategoria;
    private javax.swing.JPanel pnlListarCategoria;
    private javax.swing.JPanel pnlSouth;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTextField txtCategoriaId;
    private javax.swing.JTextField txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
